typecore: only 1k existential per match, not a 100k
Bootstrap required because:

    File "asmcomp/mach.ml", line 1:
    Error: The files asmcomp/arch.cmi and asmcomp/mach.cmi
           make inconsistent assumptions over interface Arch

which happens because:
- Arch is compiled twice, once with the bootstrapped ocamlc, once with a
  freshly compiled ocamlopt
- Arch doesn't have an .mli
- the stamp on idents won't be the same for .ml files as a result of
  this change